### PR TITLE
iotivity-node: Update to latest version (1.2.0-0)

### PR DESCRIPTION
**Pull request by rzr**
Bug: https://github.com/otcshare/iotivity-node/issues/99
Change-Id: I5d3a356e3d09bab78cb2940495e262d8f17a3b99
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by okartau** [comment]
ok to test

**Comment by rzr** [comment]
well meta-oic should be updated in ostro-os, I can try that

**Comment by mythi** [comment]
@rzr the issue is meta-oic and meta-iot-web need to be updated at the same time. I'll prepare a custom PR in ostro-os for that.

**Comment by mythi** [comment]
@rzr looks like iotivity 1.2 is not good. Ostro has an image sanity check for dangling symlinks and that detects:

```ERROR: bundle-ostro-image-swupd-world-dev-1.0-r0 do_image: Dangling symlink: /srv/jenkins/ostro-bld-10-slot-3-c2f3w/ostro-os/build/tmp-glibc/work/intel_corei7_64-ostro-linux/bundle-ostro-image-swupd-world-dev/1.0-r0/rootfs/usr/include/iotivity/resource/targets -> ../iotivity/resource/oc_logger/targets -> /srv/jenkins/ostro-bld-10-slot-3-c2f3w/ostro-os/build/tmp-glibc/work/intel_corei7_64-ostro-linux/bundle-ostro-image-swupd-world-dev/1.0-r0/rootfs/usr/include/iotivity/iotivity/resource/oc_logger/targets does not resolve to a valid filesystem entry```

**Comment by rzr** [comment]
Patch forwarded upstream to @kmaloor and can tested from this branch:
https://github.com/TizenTeam/meta-oic/commits/sandbox/pcoval/on/master/review

**Comment by rzr** [comment]
FYI. my patches for 1.2.0 just landed into 
http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic
Thanks @kmaloor

Maybe @mythi can try again to update in @ostroproject-ci ?

Linked issue:
https://github.com/otcshare/iotivity-node/issues/99

**Comment by mythi** [comment]
On Tue, Jan 24, 2017 at 7:57 PM, rzr  wrote:

> FYI. my patches for 1.2.0 just merged into
> http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic
> Thanks @kmaloor <https://github.com/kmaloor>
>
> Maybe @mythi <https://github.com/mythi> can try again to update in
> @ostroproject-ci <https://github.com/ostroproject-ci> ?
>
>
@rzr: yes, thanks! I saw that yesterday and prepared a combined test build
in ostroproject/ostro-os/pull/216 this morning.

However, there's a test case that isn't passing. I've asked @nagineni to
check.

**Comment by nagineni** [comment]
New version of iotivity-node(i.e. 1.2.0-1) and REST API server is available now. I will update both the recipes to pull in the latest changes.

**Comment by nagineni** [comment]
Replaced by https://github.com/ostroproject/meta-iot-web/pull/26

@rzr thanks a lot for your work. We have an updated version, so closing this.

**Comment by rzr** [comment]
What about 1.2.1 from meta-oic ?

**Pull request closed without merging**
