### PR TITLE
Update iotivity-node and iot-rest-api-server

### PR DESCRIPTION
**Pull request by nagineni**
Pull in the latest iotivity-node and iot-rest-api-server changes:
1. iot-rest-api-server:
   - Set Content-Type to application/json in observe request
   - Update iotivity-node dependency to v1.1.0-4
2. iotivity-node:
   - Implement findPlatforms().
   - Bring presence up-to-spec.
   - Handle malformed create(POST) requests.

Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

### CODE REVIEW

**Comment by nagineni** [comment]
@poussa

**Comment by nagineni** [comment]
Build seems to be fine, but the tests are failing and the reason might be that we disabled the startup of the rest API server on the boot.

Failing test:
oeqa.runtime.sanity.apprt_restapi.SanityTestRestApi.test_restapi_available_by_remote

Test suite must be adapted to the change to make the build green.

**Comment by pohly** [comment]
I filed an AR for the test change: IOTOS-1650

Not sure why that wasn't caught when merging the startup change?

**Comment by nagineni** [comment]
Thanks for reporting a bug. We didn't notice the test failure since the build was failing for different reasons when the startup change was merged.

**Comment by nagineni** [comment]
Buildbots are green with a fix made in the test suite:  https://github.com/ostroproject/ostro-os/pull/129

**Comment by nagineni** [comment]
Got +1 for these changes in https://github.com/ostroproject/ostro-os/pull/129. Merging.

**Pull request merged**
