### PR TITLE
iotivity-node: rename the recipe to explicitly indicate version.

### PR DESCRIPTION
**Pull request by nagineni**
Rename the recipe to explicitly indicate package version. Also, include package.json in the installation.
iotivity-node.bb -> iotivity-node_1.1.0-3.bb

Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

### CODE REVIEW

**Comment by nagineni** [comment]
@poussa

**Comment by nagineni** [comment]
This needs the fix made in https://github.com/ostroproject/meta-ostro/pull/198, so build might fail.

**Comment by nagineni** [comment]
Testing this with all required changes here: https://github.com/ostroproject/ostro-os/pull/120

**Comment by nagineni** [comment]
Build bots are green: https://ostroproject.org/jenkins/job/ostro-os_pull-requests/791/

Correct version number can be seen here: http://ostro.ostc.intel.com/download/builds/ostro-os_pull-requests/120/2016-06-07_00-35-20-build-791/sources/i686-ostro-linux/iotivity-node-1.1.0-3-r0/

**Comment by poussa** [comment]
LGTM. Pls merge.

**Pull request merged**
