### PR TITLE
recipes-web: Update iotivity-node and iot-rest-api-server to latest

### PR DESCRIPTION
**Pull request by nagineni**
SSIA

### CODE REVIEW

**Comment by mythi** [comment]
+1

**Comment by nagineni** [comment]
Build is failing due to the old version of iotivity in the repo. meta-oic and meta-iot-web needs to be updated at the same time.

**Comment by nagineni** [comment]
Merging this, so that we can integrate meta-oic and meta-iot-web at the same time.

**Comment by mythi** [comment]
@nagineni thanks! I've checked the build is OK in a combined test build in ostroproject/ostro-os/pull/216

**Comment by nagineni** [comment]
@mythi thanks for the update! :)

**Pull request merged**
