### PR TITLE
Rename packagegroup node-runtime to nodejs-runtime

### PR DESCRIPTION
**Pull request by nagineni**
Rename packagegroup-node-runtime to packagegroup-nodejs-runtime to be
consistent with the name of nodejs-runtime-tools packagegroup.

[1] This
[2] https://github.com/nagineni/meta-ostro/commit/9d0e11522 (PR will be created after [1] is in)

Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

### CODE REVIEW

**Comment by nagineni** [comment]
@mythi

**Comment by mythi** [comment]
@nagineni could you prepare [2] as well. They should be merged at the same time.

The change itself looks OK.

**Comment by nagineni** [comment]
@mythi Here is the PR for [2] - https://github.com/ostroproject/meta-ostro/pull/111

**Comment by nagineni** [comment]
@poussa

**Pull request merged**
