### PR TITLE
Update iotivity-node to latest

### PR DESCRIPTION
**Pull request by poussa**
Signed-off-by: Sakari Poussa sakari.poussa@intel.com

### CODE REVIEW

**Comment by poussa** [comment]
@mythi @nagineni PTAL

**Comment by mythi** [comment]
I tried to update this PR but got permission denied. This patch should work:

```
diff --git a/recipes-web/iotivity-node/iotivity-node.bb b/recipes-web/iotivity-node/iotivity-node.bb
index 473287a..66f0f92 100644
--- a/recipes-web/iotivity-node/iotivity-node.bb
+++ b/recipes-web/iotivity-node/iotivity-node.bb
@@ -1,14 +1,14 @@
 DESCRIPTION = "This project provides iotivity node.js bindings."
 HOMEPAGE = "https://github.com/otcshare/iotivity-node"
-LICENSE = "MIT"
+LICENSE = "Apache-2.0"

-LIC_FILES_CHKSUM = "file://${WORKDIR}/git/MIT-LICENSE.txt;md5=6b58eb710e76f8b9795f41edf589db99"
+LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/Apache-2.0;md5=89aea4e17d99a7cacdbeed46a0096b10

 DEPENDS = "nodejs-native glib-2.0 iotivity"
 RDEPENDS_${PN} += "bash iotivity-resource"

 SRC_URI = "git://github.com/otcshare/iotivity-node.git;protocol=https"
-SRCREV = "38f09bd454002b2a7f0e76b931ba80d10e37ee68"
+SRCREV = "38f76790e2d0f4960b0f3360c7bbcdf5a69907f4"

 S = "${WORKDIR}/git"
 INSANE_SKIP_${PN} += "ldflags staticdev"
@@ -73,7 +73,6 @@ do_install () {
     install -m 0644 ${S}/AUTHORS.txt ${D}${libdir}/node_modules/iotivity-node/AUTHORS.txt
     install -m 0644 ${S}/index.js ${D}${libdir}/node_modules/iotivity-node/index.js
     install -m 0644 ${S}/lowlevel.js ${D}${libdir}/node_modules/iotivity-node/lowlevel.js
-    install -m 0644 ${S}/MIT-LICENSE.txt ${D}${libdir}/node_modules/iotivity-node/MIT-LICENSE.txt
     install -m 0644 ${S}/README.md ${D}${libdir}/node_modules/iotivity-node/README.md

     cp -r ${S}/lib/ ${D}${libdir}/node_modules/iotivity-node/
```

**Comment by poussa** [comment]
@mythi relevant part of the patch is already there but now it is failing for a compile error. I'll contact Gabriel.

**Comment by poussa** [comment]
Updated the PR with Mikko's additions.

**Comment by mythi** [comment]
I've run build tests in another CI build to make sure this works. +1, merging.

**Pull request merged**
