### PR TITLE
nodejs: do not generate node.pc pkgconfig

### PR DESCRIPTION
**Pull request by mythi**
The patch to generate node.pc pkgconfig data is no longer needed so it's
better to just remove it.

The patch is also causing problems with the most recent OE-Core. More
specifically: the config_PYTHON entry that ends up written in the .pc
gets hosttools paths and the pkgconfig QA check fails.

This change basically reverts db2261cbc9ce77e38a618a835106f826e0550e60.

Signed-off-by: Mikko Ylinen <mikko.ylinen@linux.intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@nagineni PTAL

**Comment by nagineni** [comment]
LGTM. @mythi thanks for removing this.

**Comment by mythi** [comment]
@nagineni OK to merge?

**Comment by nagineni** [comment]
Yes

**Pull request merged**
