### PR TITLE
Support aarch64 architecture

### PR DESCRIPTION
**Pull request by chbae**
Dragonboard-410c and Raspberry Pi3 have 64bit arm architecture.
This commit is for supporting 64bit arm architecture.

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by chbae** [comment]
Dear reviewers

I'm contributing to GENIVI Development Platform (GDP) - http://github.com/genivi/genivi-dev-platform. However I got the build error for dragonboard-410c. So this commit is to fix it.

Then I would like to test in my dragonboard. Could you let me know how to test it? It successfully built.
GDP is using iotivity-node and iot-rest-api-server.

**Comment by gunnarx** [comment]
@chbae, I had already logged it here actually FYI:  https://at.projects.genivi.org/jira/browse/GDP-571

I think my patch is more correct actually since from what I can see node uses "arm64" as the architecture name here.  @rzr offered to help testing but he does not have a dragonboard.  Maybe you can work together?

**Comment by gunnarx** [comment]
Please see #35 which I think is right(?)

**Comment by rzr** [comment]
I am OK to merge:

https://github.com/ostroproject/meta-iot-web/pull/34/commits/3d92745ca59ca27e30adefa7db3110d90027ad4a

Note, I contacted @kmaloor about updating meta-oic to 1.2.1 as shared in list:
https://lists.iotivity.org/pipermail/iotivity-dev/2017-March/006891.html

Maybe 1.2.1 worth to be tested on meta-iot-web too ?

**Comment by chbae** [comment]
@rzr 
https://github.com/ostroproject/meta-iot-web/pull/34 and https://github.com/ostroproject/meta-iot-web/pull/35 are for same bug fix but I'm not sure which is correct. Please review two PRs and choose right one.

Also could you let me know how to test this? Then I can check those PR on my dragonboard-410c.

Thanks.

**Comment by rzr** [comment]
@chbae what do you think of @gunnarx PR #35 ?

I think adding aarch64 is better than consider arm works for 32 and 64 bits:

https://github.com/ostroproject/meta-iot-web/pull/35/commits/32e7e756dbf154f549e05cd8afdb4ecd2f4efbdf

For testing, check hints on:
http://wiki.iotivity.org/automotive

I can make you a validation test script, once it is merged.

**Comment by chbae** [comment]
@rzr I agree with you. Please merge that.

**Comment by chbae** [comment]
@rzr, @gunnarx  Thanks. I'll test it on my dragonboard.

**Pull request closed without merging**
